### ISSUE TITLE
PDF URL for stuttgart.js meetup talk was wrong (on meet up group website)

### ISSUE THREAD

**Issue by jenisys** [basti1302/talks#1]
I just noticed that the URL to the PDF version in the Meetup note was wrong (talk directory: karlsruhe.js => stuttgart.js).

MEETUP note says:
http://basti1302.github.io/talks/2016_karlsruhe.js_elm/Elm_Functional_Reactive_Programming_in_the_Browser_Bastian_Krol_StuttgartJS.pdf

but should be:
http://basti1302.github.io/talks/2016_stuttgart.js_elm/Elm_Functional_Reactive_Programming_in_the_Browser_Bastian_Krol_StuttgartJS.pdf

**Comment by basti1302** [comment]
Thanks for notifying me. Unfortunately, I already left the Stuttgart JS meetup group already (because I don't live close to Stuttgart at all) and since I am no longer a member of this meetup group, it seems, I can't even edit my old posts. The link to the online version are correct, though.
